spring.application.name=Meu Sistema

# Config padrão para ambiente local (dev),
# mas permitindo sobrescrever via variáveis de ambiente no App Runner.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/meu-sistema}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

spring.datasource.test-while-idle=true
spring.datasource.validation-query=SELECT 1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
